[package]
name = "r-type-check"
version = "0.1.0"
authors = ["rchaser53 <tayoshizawa29@gmail.com>"]
edition = "2018"

[[bin]]
name = "typecheck"
path = "src/bin/main.rs"

[dependencies]
combine = "3.8.1"
lazy_static = "1.3.0"
clap = "2.33.0"
